### PR TITLE
Fixed dependency overrides

### PR DESCRIPTION
**Pull request by davewasmer**
Packages without bower.json or package.json files were not properly accepting overrides. The lack of either file threw an exception, without checking to see if an override was provided. I added the check, and if an override is provided, a mock empty bower.json structure is returned.

### CODE REVIEW

**Comment by bclozel** [comment]
I'm very interested in this PR.
Could we also check for ".bower.json" files first? Those are generated by bower from actual bower.json files or old-format component.json files.
This would save a lot of overrides...

**Comment by ck86** [comment]
Please remove your copyrights and it would be great if you can add a test for it.

**Comment by davewasmer** [comment]
@ck86 I made these changes for a project at work, so I can't remove the copyright unfortunately. Test case is on the way.

**Comment by davewasmer** [comment]
There you are, let me know if it needs anything else.

**Comment by ck86** [comment]
I have licensed this plugin under MIT. If you are ok with it when I remove your copyrights then I will merge it.

**Comment by davewasmer** [comment]
Unfortunately, my company does not allow open source contributions to be licensed MIT. If you aren't okay with dual-licensing this project as MIT / Apache 2.0, I'd suggest closing this PR.

**Comment by ck86** [comment]
No sorry.

**Pull request closed without merging**
