### PR TITLE
Stop ignoring any part of module path

### PR DESCRIPTION
**Pull request by mikklepp**
The full module path should be used when creating the srcs. Now srcs contain entries typically with bower_components/**/foo.js, which will produce false positives. I added a test fixture to expose this.

### CODE REVIEW

**Comment by ck86** [comment]
You are right, but if 2 bower components have the same main filename and you don't want to concat all these files, just copying?

**Comment by mikklepp** [comment]
Agreed. The base needs to be provided to gulp.src via opts. I'll run with removing the dependency on bower modules and gulp-bower-files. You may use the test case provided to take this further.

**Comment by ck86** [comment]
Can be closed until gulp adds an option for the base?

**Comment by mikklepp** [comment]
There is a base option. Inherited from [glob-stream](https://github.com/wearefractal/glob-stream).

**Pull request closed without merging**
